#%RAML 1.0
---
title: Nettaton API
baseUri: http://api.nettaton.com/{version}
version: v1

/question:
  # Retrieve a new question.
  post:
    queryParameters: 
          kind:
            type: string
            description: The kind of subnet question you want to retrieve.
            example: first
            required: false
  /{id}:
    # Get the question by id.
    get:
    /answer:
      # Answer question.
      post: