#%RAML 1.0
---
title: Nettaton API
baseUri: http://api.nettaton.com/{version}
version: v1

/subnet-questions:
  # Retrieve a new question.
  post:
    queryParameters: 
          question-kind:
            type: string
            description: The kind of subnet question you want to retrieve.
            example: first
            required: false
  /{question-id}:
    # Get or delete the question by id.
    get:
    /answer:
      # Answer question.
      post: