#%RAML 1.0
---
title: Nettaton API
baseUri: http://api.nettaton.com/{version}
version: v1

/question:
  # Create a new question, this question will be stored server side.
  # The question expires after a few hours.
  post:
    queryParameters: 
          kind:
            type: string
            description: The kind of subnet question you want to retrieve.
            example: first
            required: false
  /{id}:
    # Read the question by id.
    get:
    /answer:
      # Answer question by id. If answered successfully this deletes the 
      # question from the database.
      post: